# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def shared_pods
  pod "HTMLReader"
end

target 'RSSReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  # Pods for RSSReader
  shared_pods

  target 'RSSReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RSSReaderUITests' do
    # Pods for testing
  end

end
